
version: "2.0"

services:
  jupyterlab_simple:
    container_name: ${NAME}
    build: .
    restart: always
    user: root
    # privileged: true
    shm_size: '4gb'
    working_dir: /home/jovyan/work/
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${UID}
      NB_GID: ${GID}
    ports:
      - ${PORT}:8888
    volumes:
      - ${WORK_DIR}:/home/jovyan/work
      - /etc/localtime:/etc/localtime
